In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('data/movie_budgets.csv')

In [ ]:
df['earnings'] = ['']

In [13]:
df.head(20)

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
5,6,"Dec 18, 2015",Star Wars Ep. VII: The Force Awakens,"$306,000,000","$936,662,225","$2,053,311,220"
6,7,"Apr 27, 2018",Avengers: Infinity War,"$300,000,000","$678,815,482","$2,048,134,200"
7,8,"May 24, 2007",Pirates of the Caribbean: At Worldâs End,"$300,000,000","$309,420,425","$963,420,425"
8,9,"Nov 17, 2017",Justice League,"$300,000,000","$229,024,295","$655,945,209"
9,10,"Nov 6, 2015",Spectre,"$300,000,000","$200,074,175","$879,620,923"
10,11,"Jul 20, 2012",The Dark Knight Rises,"$275,000,000","$448,139,099","$1,084,439,099"
11,12,"May 25, 2018",Solo: A Star Wars Story,"$275,000,000","$213,767,512","$393,151,347"
12,13,"Jul 2, 2013",The Lone Ranger,"$275,000,000","$89,302,115","$260,002,115"
13,14,"Mar 9, 2012",John Carter,"$275,000,000","$73,058,679","$282,778,100"
14,15,"Nov 24, 2010",Tangled,"$260,000,000","$200,821,936","$586,477,240"
15,16,"May 4, 2007",Spider-Man 3,"$258,000,000","$336,530,303","$894,860,230"
16,17,"May 6, 2016",Captain America: Civil War,"$250,000,000","$408,084,349","$1,140,069,413"
17,18,"Mar 25, 2016",Batman v Superman: Dawn of Justice,"$250,000,000","$330,360,194","$867,500,281"
18,19,"Dec 14, 2012",The Hobbit: An Unexpected Journey,"$250,000,000","$303,003,568","$1,017,003,568"
19,20,"Jul 15, 2009",Harry Potter and the Half-Blood Prince,"$250,000,000","$302,089,278","$935,213,767"

In [5]:
ratings = pd.read_csv('data/rotten_tomatoes_movies.csv')
ratings.head(10)

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
1,m/0878835,Please Give,Kate (Catherine Keener) and her husband Alex (...,Nicole Holofcener's newest might seem slight i...,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",2010-04-30,...,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,44,123,19
2,m/10,10,"A successful, middle-aged Hollywood songwriter...",Blake Edwards' bawdy comedy may not score a pe...,R,"Comedy, Romance",Blake Edwards,Blake Edwards,"Dudley Moore, Bo Derek, Julie Andrews, Robert ...",1979-10-05,...,Waner Bros.,Fresh,67.0,24.0,Spilled,53.0,14684.0,2,16,8
3,m/1000013-12_angry_men,12 Angry Men (Twelve Angry Men),Following the closing arguments in a murder tr...,Sidney Lumet's feature debut is a superbly wri...,NR,"Classics, Drama",Sidney Lumet,Reginald Rose,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",1957-04-13,...,Criterion Collection,Certified-Fresh,100.0,54.0,Upright,97.0,105386.0,6,54,0
4,m/1000079-20000_leagues_under_the_sea,"20,000 Leagues Under The Sea","In 1866, Professor Pierre M. Aronnax (Paul Luk...","One of Disney's finest live-action adventures,...",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",1954-01-01,...,Disney,Fresh,89.0,27.0,Upright,74.0,68918.0,5,24,3
5,m/10000_bc,"10,000 B.C.",Mammoth hunter D'Leh (Steven Strait) has long ...,With attention strictly paid to style instead ...,PG-13,"Action & Adventure, Classics, Drama",Roland Emmerich,"Harald Kloser, Roland Emmerich","Steven Strait, Camilla Belle, Cliff Curtis, Jo...",2008-03-07,...,Warner Bros. Pictures,Rotten,8.0,149.0,Spilled,37.0,411140.0,37,12,137
6,m/1000121-39_steps,The 39 Steps,"While on vacation in London, Canadian Richard ...","Packed with twists and turns, this essential e...",NR,"Action & Adventure, Classics, Mystery & Suspense",Alfred Hitchcock,"Alma Reville, Charles Bennett, Ian Hay, Alfred...","Robert Donat, Madeleine Carroll, Godfrey Tearl...",1935-08-01,...,Gaumont British Distributors,Certified-Fresh,96.0,51.0,Upright,86.0,23890.0,8,49,2
7,m/1000123-310_to_yuma,3:10 to Yuma,"Dan Evans (Van Heflin), a drought-plagued Ariz...",NaN,NR,"Classics, Drama, Western",Delmer Daves,Halsted Welles,"Glenn Ford, Van Heflin, Felicia Farr, Leora Da...",1957-08-07,...,Columbia Pictures,Fresh,96.0,28.0,Upright,79.0,9243.0,6,27,1
8,m/10002008-charly,Charly (A Heartbeat Away),"Cultural differences, past loves and personal ...",NaN,PG,"Comedy, Drama, Romance",Adam Thomas Anderegg,"Jack Weyland, Janine Whetton Gilbert","Heather Beers, Gary Neilson, Lisa McCammon, Ja...",2002-09-27,...,Excel Entertainment,Rotten,20.0,10.0,Upright,87.0,4819.0,0,2,8
9,m/1000204-abraham_lincoln,Abraham Lincoln,The 16th U.S. president (Walter Huston) is por...,NaN,NR,"Classics, Drama",D.W. Griffith,"Gerrit J. Lloyd, Stephen Vincent Benét","Walter Huston, Una Merkel, Kay Hammond, Ian Ke...",1930-11-08,...,United Artists,Fresh,82.0,11.0,Spilled,40.0,457.0,4,9,2

In [32]:
ratings['tomatometer_status'].value_counts()

Rotten             7565
Fresh              6844
Certified-Fresh    3259
Name: tomatometer_status, dtype: int64

In [33]:
ratings['audience_status'].value_counts()

Upright    9390
Spilled    7874
Name: audience_status, dtype: int64

In [49]:
highestaudiencerating = ratings.sort_values(by =['audience_count' , 'audience_rating'], ascending= False)
highestaudiencerating.head(30)

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
16297,m/titanic,Titanic,"James Cameron's ""Titanic"" is an epic, action-p...",A mostly unqualified triumph for James Cameron...,PG-13,"Drama, Romance",James Cameron,James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane, K...",1997-12-19,...,Paramount Pictures,Certified-Fresh,89.0,192.0,Upright,69.0,35797635.0,62,171,21
15410,m/the_lord_of_the_rings_the_return_of_the_king,The Lord of the Rings: The Return of the King,The culmination of nearly 10 years' work and c...,Visually breathtaking and emotionally powerful...,PG-13,"Action & Adventure, Classics, Science Fiction ...",Peter Jackson,"Fran Walsh, Philippa Boyens, Peter Jackson","Elijah Wood, Sean Astin, Ian McKellen, Andy Se...",2003-12-17,...,New Line Cinema,Certified-Fresh,93.0,275.0,Upright,86.0,34679773.0,53,257,18
13694,m/spiderman,Spider-Man,"""Spider-Man"" centers on student Peter Parker (...",Not only does Spider-Man provide a good dose o...,PG-13,"Action & Adventure, Mystery & Suspense, Scienc...",Sam Raimi,David Koepp,"Tobey Maguire, Kirsten Dunst, Willem Dafoe, Ja...",2002-05-03,...,Columbia Pictures,Certified-Fresh,90.0,245.0,Upright,67.0,34297354.0,47,220,25
13276,m/shrek_2,Shrek 2,After returning from their honeymoon and showi...,"It may not be as fresh as the original, but to...",PG,"Animation, Comedy, Kids & Family, Science Fict...","Conrad Vernon, Andrew Adamson, Kelly Asbury","Joe Stillman, David N. Weiss, J. David Stern, ...","Mike Myers, John Cleese, Jonathan Ross, Jennif...",2004-05-19,...,Dreamworks,Certified-Fresh,89.0,236.0,Upright,69.0,34232524.0,53,209,27
7526,m/harry_potter_and_the_goblet_of_fire,Harry Potter and the Goblet of Fire,The fourth movie in the Harry Potter franchise...,"The main characters are maturing, and the film...",PG-13,"Action & Adventure, Kids & Family, Science Fic...",Mike Newell,Steve Kloves,"Daniel Radcliffe, Rupert Grint, Emma Watson, R...",2005-11-18,...,Warner Bros. Pictures,Certified-Fresh,88.0,255.0,Upright,74.0,34153607.0,53,224,31
7052,m/gladiator,Gladiator,Commodus (Joaquin Phoenix) takes power and str...,Ridley Scott and an excellent cast successfull...,R,"Action & Adventure, Classics, Drama",Ridley Scott,"David H. Franzoni, William Nicholson, John Logan","Russell Crowe, Joaquin Phoenix, Connie Nielsen...",2000-05-05,...,Dreamworks Distribution LLC,Certified-Fresh,77.0,199.0,Upright,87.0,34128168.0,49,153,46
4579,m/chronicles_of_narnia_lion_witch_wardrobe,"The Chronicles of Narnia: The Lion, The Witch ...","During the World War II bombings of London, fo...",With first-rate special effects and compelling...,PG,"Kids & Family, Science Fiction & Fantasy",Andrew Adamson,"Ann Peacock, Andrew Adamson, Christopher Marku...","Georgie Henley, Skandar Keynes, William Mosele...",2005-12-09,...,Buena Vista,Certified-Fresh,76.0,218.0,Upright,61.0,34105114.0,48,166,52
2662,m/american_pie,American Pie,A riotous and raunchy exploration of the most ...,"So embarrassing it's believable, American Pie ...",R,Comedy,"Paul Weitz, Chris Weitz","Adam Herz, Paul Weitz","Jason Biggs, Mena Suvari, Alyson Hannigan, Sha...",1999-07-09,...,Universal Pictures,Fresh,61.0,129.0,Upright,61.0,33781574.0,29,79,50
9014,m/king_kong,King Kong,Peter Jackson's expansive remake of the 1933 c...,"Featuring state-of-the-art special effects, te...",PG-13,Action & Adventure,Peter Jackson,"Fran Walsh, Philippa Boyens, Peter Jackson","Naomi Watts, Jack Black, Adrien Brody, Thomas ...",2005-12-14,...,Universal Pictures,Certified-Fresh,84.0,267.0,Spilled,50.0,33766734.0,50,224,43
13797,m/star_wars_episode_iii_revenge_of_the_sith,Star Wars: Episode III - Revenge of the Sith,It has been three years since the Clone Wars b...,"With Episode III: Revenge of the Sith, George ...",PG-13,"Action & Adventure, Drama, Science Fiction & F...",George Lucas,George Lucas,"Ewan McGregor, Natalie Portman, Hayden Christe...",2005-05-19,...,20th Century Fox,Certified-Fresh,80.0,299.0,Upright,66.0,33683838.0,59,239,60
10655,m/mr_and_mrs_smith,Mr. & Mrs. Smith,John (Brad Pitt) and Jane Smith (Angelina Joli...,Although this action-romance suffers from weak...,PG-13,"Action & Adventure, Comedy, Mystery & Suspense",Doug Liman,Simon Kinberg,"Brad Pitt, Angelina Jolie, Vince Vaughn, Adam ...",2005-06-07,...,20th Century Fox,Fresh,60.0,214.0,Spilled,58.0,33461707.0,48,128,86
701,m/1017776-rocky,Rocky,"Rocky Balboa (Sylvester Stallone), a small-tim...",This story of a down-on-his-luck boxer is thor...,PG,"Drama, Sports & Fitness",John G. Avildsen,Sylvester Stallone,"Sylvester Stallone, Talia Shire, Burt Young, C...",1976-11-21,...,United Artists,Certified-Fresh,94.0,65.0,Upright,69.0,33403994.0,11,61,4
6453,m/finding_nemo,Finding Nemo,"Marlin (Albert Brooks), a clown fish, is overl...",Breathtakingly lovely and grounded by the stel...,G,"Animation, Comedy, Kids & Family","Andrew Stanton, Lee Unkrich","Bob Peterson, David Reynolds, Andrew Stanton, ...","Albert Brooks, Ellen DeGeneres, Alexander Goul...",2003-05-30,...,Walt Disney Pictures,Certified-Fresh,99.0,266.0,Upright,86.0,33356856.0,61,264,2
10183,m/matrix,The Matrix,Neo (Keanu Reeves) believes that Morpheus (Lau...,"Thanks to the Wachowskis' imaginative vision, ...",R,"Action & Adventure, Science Fiction & Fantasy","Lilly Wachowski, Lana Wachowski","Lana Wachowski, Lilly Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...",1999-03-31,...,Warner Bros. Pictures,Certified-Fresh,88.0,154.0,Upright,85.0,33324202.0,37,135,19
2313,m/ace_ventura_pet_detective,Ace Ventura: Pet Detective,When the dolphin mascot of Miami's NFL team is...,Jim Carrey's twitchy antics and gross-out humo...,PG-13,"Action & Adventure, Comedy",Tom Shadyac,"Jim Carrey, Tom Shadyac, Jack B. Bernstein","Jim Carrey, Courteney Cox, Sean Young, Dan Mar...",1993-06-01,...,Warner Bros. Pictures,Rotten,49.0,61.0,Spilled,57.0,33204120.0,12,30,31
10260,m/meet_the_fockers,Meet the Fockers,"Now that Greg Focker is ""in"" with his soon-to-...",Talented cast is wasted as the movie is conten...,PG-13,Comedy,Jay Roach,"Jim Herzfeld, John Hamburg, Jay Roach","Robert De Niro, Ben Stiller, Dustin Hoffman, B...",2004-12-22,...,Universal Pictures,Rotten,39.0,162.0,Spilled,58.0,33181885.0,41,63,99
11866,m/pirates_of_the_caribbean_the_curse_of_the_bl...,Pirates of the Caribbean: The Curse of the Bla...,Capt. Jack Sparrow (Johnny Depp) arrives at Po...,May leave you exhausted like the theme park ri...,PG-13,"Action & Adventure, Science Fiction & Fantasy",Gore Verbinski,"Ted Elliott, Terry Rossio","Johnny Depp, Geoffrey Rush, Orlando Bloom, Kei...",2003-06-28,...,Buena Vista Pictures,Certified-Fresh,79.0,219.0,Upright,86.0,33125722.0,45,173,46
16106,m/theres_something_about_mary,There's Something About Mary,Ted's (Ben Stiller) dream prom date with Mary ...,There's Something About Mary proves that unrel...,R,Comedy,"Bobby Farrelly, Peter Farrelly","Bobby Farrelly, Peter Farrelly, Edward Decter,...","Cameron Diaz, Ben Stiller, Matt Dillon, Chris ...",1998-07-15,...,20th Century Fox,Certified-Fresh,83.0,84.0,Upright,61.0,33121539.0,24,70,14
4101,m/bruce_almighty,Bruce Almighty,Bruce Nolan's (Jim Carrey) career in TV has be...,"Carrey is hilarious in the slapstick scenes, b...",PG-13,"Comedy, Science Fiction & Fantasy",Tom Shadyac,"Mark O'Keefe, Steve Koren, Steve Oedekerk","Jim Carrey, Morgan Freeman, Jennifer Aniston, ...",2003-05-23,...,Universal Pictures,Rotten,48.0,193.0,Spilled,57.0,33024215.0,44,93,100
17120,m/wedding_crashers,Wedding Crashers,Jeremy (Vince Vaughn) and John (Owen Wilson) a...,"Wedding Crashers is both raunchy and sweet, an...",R,"Comedy, Romance",David Dobkin,"Steve Faber, Bob Fisher, David Dobkin","Owen Wilson, Vince Vaughn, Rachel McAdams, Chr...",2005-07-15,...,New Line Cinema,Certified-Fresh,76.0,188.0,Upright,70.0,32961772.0,47,142,46
3010,m/austin_powers_in_goldmember,Austin Powers in Goldmember,Teaming up with the mysterious yet peculiar Go...,While the narrative structure is messy and doe...,PG-13,Comedy,NaN,NaN,NaN,2002-07-25,...,New Line Cinema,Rotten,53.0,187.0,Spilled,44.0,32935203.0,39,100,87
1949,m/2_fast_2_furious,2 Fast 2 Furious,This sequel focuses on ex-police officer Brian...,Beautiful people and beautiful cars in a movie...,PG-13,"Action & Adventure, Drama, Mystery & Suspense",John Singleton,"Gary Scott Thompson, Derek Haas, Michael Brandt","Paul Walker, Tyrese Gibson, Eva Mendes, Cole H...",2003-06-06,...,Universal Pictures Distributio,Rotten,36.0,160.0,Spilled,50.0,32791717.0,38,58,102
12942,m/school_of_rock,School of Rock,Overly enthusiastic guitarist Dewey Finn (Jack...,"Black's exuberant, gleeful performance turns S...",PG-13,Comedy,Richard Linklater,"Mike White, Richard Linklater","Jack Black, Mike White, Joan Cusack, Sarah Sil...",2003-10-03,...,Paramount Pictures,Certified-Fresh,91.0,199.0,Upright,64.0,32784354.0,43,182,17
9682,m/longest_yard,The Longest Yard,Disgraced pro football quarterback Paul Crewe ...,This Yard has some laughs but missing from thi...,PG-13,"Comedy, Drama",Peter Segal,"Tracey Keenan Wynn, Sheldon Turner","Adam Sandler, Chris Rock, Burt Reynolds, James...",2005-05-27,...,Paramount Pictures,Rotten,31.0,169.0,Upright,62.0,32774364.0,40,53,116
5211,m/day_after_tomorrow,The Day After Tomorrow,After climatologist Jack Hall (Dennis Quaid) i...,The Day After Tomorrow is a ludicrous popcorn ...,PG-13,"Action & Adventure, Drama, Mystery & Suspense,...",Roland Emmerich,"Jeffrey Nachmanoff, Roland Emmerich","Dennis Quaid, Jake Gyllenhaal, Emmy Rossum, Da...",2004-05-28,...,20th Century Fox,Rotten,44.0,221.0,Spilled,50.0,32749429.0,45,98,123
12029,m/pretty_woman,Pretty Woman,"In this modern update on Cinderella, a prostit...","Pretty Woman may be a yuppie fantasy, but the ...",R,"Comedy, Romance",Garry Marshall,J.F. Lawton,"Julia Roberts, Richard Gere, Hector Elizondo, ...",1990-03-23,...,Buena Vista,Fresh,63.0,68.0,Upright,68.0,32709375.0,15,43,25
1051,m/1065684-braveheart,Braveheart,Tells the story of the legendary thirteenth ce...,"Distractingly violent and historically dodgy, ...",R,"Action & Adventure, Classics, Drama",Mel Gibson,Randall Wallace,"Mel Gibson, Sophie Marceau, Patrick McGoohan, ...",1995-05-26,...,Paramount Pictures,Certified-Fresh,78.0,82.0,Upright,85.0,32708456.0,27,64,18
2009,m/50_first_dates,50 First Dates,Playboy vet Henry sets his heart on romancing ...,Gross-out humor overwhelms the easy chemistry ...,PG-13,Comedy,Peter Segal,George Wing,"Adam Sandler, Drew Barrymore, Rob Schneider, S...",2004-02-13,...,Sony Pictures,Rotten,45.0,176.0,Upright,65.0,32700188.0,41,79,97
17283,m/white_chicks,White Chicks,"Two FBI agent brothers, Marcus (Marlon Wayans)...",Scattershot comedy that's silly and obvious.,PG-13,Comedy,Keenen Ivory Wayans,"Keenen Ivory Wayans, Shawn Wayans, Andy McElfr...","Shawn Wayans, Marlon Wayans, Jaime King, Frank...",2004-06-23,...,Columbia Pictures,Rotten,15.0,124.0,Spilled,55.0,32691607.0,35,18,106
7780,m/hitch,Hitch,"Dating coach Alex ""Hitch"" Hitchens (Will Smith...","Despite Hitch's predictability, Will Smith and...",PG-13,"Comedy, Romance","Andrew Tennant, Andy Tennant",Kevin Bisch,"Will Smith, Eva Mendes, Kevin James, Amber Val...",2005-02-11,...,Sony Pictures,Fresh,69.0,188.0,Upright,62.0,32624083.0,39,129,59

In [18]:
critic_reviews = pd.read_csv('data/rotten_tomatoes_critic_reviews.csv')
critic_reviews.head(10)

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."
2,m/0814255,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...
3,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
4,m/0814255,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...
5,m/0814255,David Germain,True,Associated Press,Rotten,NaN,2010-02-10,It's more a list of ingredients than a movie-m...
6,m/0814255,Nick Schager,False,Slant Magazine,Rotten,1/4,2010-02-10,Harry Potter knockoffs don't come more transpa...
7,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,3.5/5,2010-02-10,"Percy Jackson isn't a great movie, but it's a ..."
8,m/0814255,Jordan Hoffman,False,UGO,Fresh,B,2010-02-10,"Fun, brisk and imaginative"
9,m/0814255,Jim Schembri,True,The Age (Australia),Fresh,3/5,2010-02-10,"Crammed with dragons, set-destroying fights an..."

In [19]:
critic_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1130017 entries, 0 to 1130016
Data columns (total 8 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   rotten_tomatoes_link  1130017 non-null  object
 1   critic_name           1111488 non-null  object
 2   top_critic            1130017 non-null  bool
 3   publisher_name        1130017 non-null  object
 4   review_type           1130017 non-null  object
 5   review_score          824081 non-null   object
 6   review_date           1130017 non-null  object
 7   review_content        1064211 non-null  object
dtypes: bool(1), object(7)
memory usage: 61.4+ MB

In [54]:
movie_gross = pd.read_csv('data/bom.movie_gross.csv')
movie_gross.head(10)

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
5,The Twilight Saga: Eclipse,Sum.,300500000.0,398000000,2010
6,Iron Man 2,Par.,312400000.0,311500000,2010
7,Tangled,BV,200800000.0,391000000,2010
8,Despicable Me,Uni.,251500000.0,291600000,2010
9,How to Train Your Dragon,P/DW,217600000.0,277300000,2010

In [26]:
tmdsb = pd.read_csv('data/tmdsb.movies.csv')
tmdsb.head()

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186

In [53]:
high_popularity= tmdsb.sort_values(by= ['popularity', 'vote_count', 'vote_average'], ascending= False )
high_popularity.head(30)
#based on this table, which is based on popularity, vote count, and vote average (in that order), it seems that the action
#genre is the most popular

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
23811,"[12, 28, 14]",299536,en,Avengers: Infinity War,80.773,2018-04-27,Avengers: Infinity War,8.3,13948
11019,"[28, 53]",245891,en,John Wick,78.123,2014-10-24,John Wick,7.2,10081
23812,"[28, 12, 16, 878, 35]",324857,en,Spider-Man: Into the Spider-Verse,60.534,2018-12-14,Spider-Man: Into the Spider-Verse,8.4,4048
11020,"[28, 12, 14]",122917,en,The Hobbit: The Battle of the Five Armies,53.783,2014-12-17,The Hobbit: The Battle of the Five Armies,7.3,8392
5179,"[878, 28, 12]",24428,en,The Avengers,50.289,2012-05-04,The Avengers,7.6,19673
11021,"[28, 878, 12]",118340,en,Guardians of the Galaxy,49.606,2014-08-01,Guardians of the Galaxy,7.9,17958
20617,"[878, 28, 53]",335984,en,Blade Runner 2049,48.571,2017-10-06,Blade Runner 2049,7.4,6679
23813,"[878, 28, 53]",335984,en,Blade Runner 2049,48.571,2017-10-06,Blade Runner 2049,7.4,6679
23814,[12],338952,en,Fantastic Beasts: The Crimes of Grindelwald,48.508,2018-11-16,Fantastic Beasts: The Crimes of Grindelwald,6.9,4870
23815,"[10751, 16, 35, 14, 12]",404368,en,Ralph Breaks the Internet,48.057,2018-11-21,Ralph Breaks the Internet,7.2,2626
20618,"[28, 12, 878, 18]",315635,en,Spider-Man: Homecoming,46.775,2017-07-07,Spider-Man: Homecoming,7.4,11585
20619,"[53, 28, 80]",324552,en,John Wick: Chapter 2,45.253,2017-02-10,John Wick: Chapter 2,7.0,5863
20620,"[28, 18, 878]",263115,en,Logan,45.000,2017-03-03,Logan,7.8,12330
23816,"[28, 12, 878, 35]",363088,en,Ant-Man and the Wasp,44.729,2018-07-06,Ant-Man and the Wasp,7.0,6290
14169,"[28, 12, 878]",99861,en,Avengers: Age of Ultron,44.383,2015-05-01,Avengers: Age of Ultron,7.3,13457
23817,"[28, 12, 14, 878]",284054,en,Black Panther,44.140,2018-02-16,Black Panther,7.4,12365
23818,"[878, 28]",335983,en,Venom,44.007,2018-10-05,Venom,6.6,6206
20621,"[28, 12, 35, 14]",284053,en,Thor: Ragnarok,43.450,2017-11-03,Thor: Ragnarok,7.5,11380
23819,"[28, 12, 35, 14]",284053,en,Thor: Ragnarok,43.450,2017-11-03,Thor: Ragnarok,7.5,11380
23820,"[28, 12, 878]",424783,en,Bumblebee,43.078,2018-12-21,Bumblebee,6.5,2425
11022,"[28, 12, 14, 878]",127585,en,X-Men: Days of Future Past,41.867,2014-05-23,X-Men: Days of Future Past,7.5,10062
20622,"[28, 12, 35, 878]",283995,en,Guardians of the Galaxy Vol. 2,40.228,2017-05-05,Guardians of the Galaxy Vol. 2,7.7,12535
23821,"[12, 14]",428078,en,Mortal Engines,40.095,2018-12-14,Mortal Engines,6.0,1751
23822,"[12, 28, 53]",375588,en,Robin Hood,39.975,2018-11-21,Robin Hood,5.8,1194
17381,"[28, 12, 878, 14]",246655,en,X-Men: Apocalypse,39.293,2016-05-27,X-Men: Apocalypse,6.5,8348
17382,"[12, 28, 878]",271110,en,Captain America: Civil War,39.137,2016-05-06,Captain America: Civil War,7.4,14000
23823,"[28, 35, 12]",383498,en,Deadpool 2,38.894,2018-05-10,Deadpool 2,7.5,8773
23824,"[28, 12, 14]",297802,en,Aquaman,38.102,2018-12-21,Aquaman,6.8,6155
2468,"[12, 14, 28]",10195,en,Thor,38.068,2011-05-06,Thor,6.7,12764
23825,"[18, 10402]",424694,en,Bohemian Rhapsody,37.197,2018-11-02,Bohemian Rhapsody,8.1,7629

In [28]:
name_basics = pd.read_csv('data/name.basics.csv')
name_basics.head()

,nconst,primary_name,birth_year,death_year,primary_profession,known_for_titles
0,nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer","tt0837562,tt2398241,tt0844471,tt0118553"
1,nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department","tt0896534,tt6791238,tt0287072,tt1682940"
2,nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer","tt1470654,tt0363631,tt0104030,tt0102898"
3,nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department","tt0114371,tt2004304,tt1618448,tt1224387"
4,nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator","tt0452644,tt0452692,tt3458030,tt2178256"

In [56]:
tmdb_movies= pd.read_csv('data/tmdb_movies_data.csv')
tmdb_movies.head(10)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,1.747999e+08,1.385749e+09
5,281957,tt1663202,9.110700,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)",...,"In the 1820s, a frontiersman, Hugh Glass, sets...",156,Western|Drama|Adventure|Thriller,Regency Enterprises|Appian Way|CatchPlay|Anony...,12/25/2015,3929,7.2,2015,1.241999e+08,4.903142e+08
6,87101,tt1340138,8.654359,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,...,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,6/23/2015,2598,5.8,2015,1.425999e+08,4.053551e+08
7,286217,tt3659388,7.667400,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,...,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,9/30/2015,4572,7.6,2015,9.935996e+07,5.477497e+08
8,211672,tt2293640,7.404165,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",...,"Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,6/17/2015,2893,6.5,2015,6.807997e+07,1.064192e+09
9,150540,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,...,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,3935,8.0,2015,1.609999e+08,7.854116e+08

In [60]:
cleaned_tmdb= tmdb_movies.sort_values(by= ['vote_count', 'vote_average','popularity', 'revenue'], ascending= False)

In [61]:
cleaned_tmdb.head(10)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
1919,27205,tt1375666,9.363643,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,http://inceptionmovie.warnerbros.com/,Christopher Nolan,Your mind is the scene of the crime.,...,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,9767,7.9,2010,1.600000e+08,8.255000e+08
4361,24428,tt0848228,7.637767,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,http://marvel.com/avengers_movie/,Joss Whedon,Some assembly required.,...,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,8903,7.3,2012,2.089437e+08,1.443191e+09
1386,19995,tt0499549,9.432768,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,http://www.avatarmovie.com/,James Cameron,Enter the World of Pandora.,...,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,8458,7.1,2009,2.408869e+08,2.827124e+09
2875,155,tt0468569,8.466668,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,http://thedarkknight.warnerbros.com/dvdsite/,Christopher Nolan,Why So Serious?,...,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8432,8.1,2008,1.873655e+08,1.014733e+09
4364,68718,tt1853728,5.944518,100000000,425368238,Django Unchained,Jamie Foxx|Christoph Waltz|Leonardo DiCaprio|K...,http://unchainedmovie.com/,Quentin Tarantino,"Life, liberty and the pursuit of vengeance.",...,"With the help of a German bounty hunter, a fre...",165,Drama|Western,Columbia Pictures|The Weinstein Company,12/25/2012,7375,7.7,2012,9.497443e+07,4.039911e+08
4382,70160,tt1392170,2.571099,75000000,691210692,The Hunger Games,Jennifer Lawrence|Josh Hutcherson|Liam Hemswor...,http://www.thehungergames.movie/,Gary Ross,May The Odds Be Ever In Your Favor.,...,Every year in the ruins of what was once North...,142,Science Fiction|Adventure|Fantasy,Lionsgate|Color Force,3/12/2012,7080,6.7,2012,7.123082e+07,6.564734e+08
5425,68721,tt1300854,4.946136,200000000,1215439994,Iron Man 3,Robert Downey Jr.|Gwyneth Paltrow|Guy Pearce|D...,http://marvel.com/ironman3,Shane Black,Unleash the power behind the armor.,...,When Tony Stark's world is torn apart by a for...,130,Action|Adventure|Science Fiction,Marvel Studios,4/18/2013,6882,6.9,2013,1.872067e+08,1.137692e+09
4363,49026,tt1345836,6.591277,250000000,1081041287,The Dark Knight Rises,Christian Bale|Michael Caine|Gary Oldman|Anne ...,http://www.thedarkknightrises.com/,Christopher Nolan,The Legend Ends,...,Following the death of District Attorney Harve...,165,Action|Crime|Drama|Thriller,Legendary Pictures|Warner Bros.|DC Entertainme...,7/16/2012,6723,7.5,2012,2.374361e+08,1.026713e+09
629,157336,tt0816692,24.949134,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,http://www.interstellarmovie.net/,Christopher Nolan,Mankind was born on Earth. It was never meant ...,...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,6498,8.0,2014,1.519800e+08,5.726906e+08
4367,49051,tt0903624,4.218933,250000000,1017003568,The Hobbit: An Unexpected Journey,Ian McKellen|Martin Freeman|Richard Armitage|A...,http://www.thehobbit.com/,Peter Jackson,From the smallest beginnings come the greatest...,...,"Bilbo Baggins, a hobbit enjoying his quiet lif...",169,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|Metro-Goldwyn-Ma...,11/26/2012,6417,6.9,2012,2.374361e+08,9.658933e+08

In [66]:
cleaned_tmdbs= cleaned_tmdb.drop(['cast', 'homepage', 'tagline', 'overview', 'production_companies', 'keywords'], axis=1)
cleaned_tmdbs.head()
#We got rid of columns that were not needed in order for us to make conclusions on the data

,id,imdb_id,popularity,budget,revenue,original_title,director,runtime,genres,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
1919,27205,tt1375666,9.363643,160000000,825500000,Inception,Christopher Nolan,148,Action|Thriller|Science Fiction|Mystery|Adventure,7/14/2010,9767,7.9,2010,1.600000e+08,8.255000e+08
4361,24428,tt0848228,7.637767,220000000,1519557910,The Avengers,Joss Whedon,143,Science Fiction|Action|Adventure,4/25/2012,8903,7.3,2012,2.089437e+08,1.443191e+09
1386,19995,tt0499549,9.432768,237000000,2781505847,Avatar,James Cameron,162,Action|Adventure|Fantasy|Science Fiction,12/10/2009,8458,7.1,2009,2.408869e+08,2.827124e+09
2875,155,tt0468569,8.466668,185000000,1001921825,The Dark Knight,Christopher Nolan,152,Drama|Action|Crime|Thriller,7/16/2008,8432,8.1,2008,1.873655e+08,1.014733e+09
4364,68718,tt1853728,5.944518,100000000,425368238,Django Unchained,Quentin Tarantino,165,Drama|Western,12/25/2012,7375,7.7,2012,9.497443e+07,4.039911e+08

In [72]:
cleaned_tmdbs_filtered= cleaned_tmdbs[cleaned_tmdbs['budget'] >= 5]
#filtering through the data to get rid of rows that have null values or zero put in as a placeholder for budget and revenue33

In [73]:
cleaned_tmdbs_filtered

,id,imdb_id,popularity,budget,revenue,original_title,director,runtime,genres,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
1919,27205,tt1375666,9.363643,160000000,825500000,Inception,Christopher Nolan,148,Action|Thriller|Science Fiction|Mystery|Adventure,7/14/2010,9767,7.9,2010,1.600000e+08,8.255000e+08
4361,24428,tt0848228,7.637767,220000000,1519557910,The Avengers,Joss Whedon,143,Science Fiction|Action|Adventure,4/25/2012,8903,7.3,2012,2.089437e+08,1.443191e+09
1386,19995,tt0499549,9.432768,237000000,2781505847,Avatar,James Cameron,162,Action|Adventure|Fantasy|Science Fiction,12/10/2009,8458,7.1,2009,2.408869e+08,2.827124e+09
2875,155,tt0468569,8.466668,185000000,1001921825,The Dark Knight,Christopher Nolan,152,Drama|Action|Crime|Thriller,7/16/2008,8432,8.1,2008,1.873655e+08,1.014733e+09
4364,68718,tt1853728,5.944518,100000000,425368238,Django Unchained,Quentin Tarantino,165,Drama|Western,12/25/2012,7375,7.7,2012,9.497443e+07,4.039911e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5818,182228,tt2538128,0.265782,500000,0,100 Degrees Below Zero,R.D. Braunstein,88,Action|Science Fiction,3/29/2013,10,3.7,2013,4.680167e+05,0.000000e+00
6476,12261,tt0427038,0.182135,9000000,0,Carlito's Way: Rise to Power,Michael Bregman,100,Action|Adventure|Drama|Thriller,9/27/2005,10,3.7,2005,1.004907e+07,0.000000e+00
2855,19058,tt0247303,0.128169,15000000,163169,Down,Dick Maas,111,Action|Horror|Mystery|Thriller,5/11/2001,10,3.7,2001,1.847232e+07,2.009407e+05
1880,20236,tt1182609,0.077477,6000000,0,Direct Contact,Danny Lerner,90,Action|Adventure|Thriller,4/16/2009,10,3.5,2009,6.098403e+06,0.000000e+00
10659,4255,tt0065904,0.344172,5000,0,The Party at Kitty and Stud's,Morton Lewis,71,NaN,2/10/1970,10,3.0,1970,2.808184e+04,0.000000e+00

In [76]:
cleaned_revenue = cleaned_tmdbs[cleaned_tmdbs.revenue != 0]
filtered_tmdbs= cleaned_revenue[cleaned_revenue.budget !=0 ]

In [85]:
filtered_tmdbs
#got rid of all movies that had 0 for either budget or revenue

,id,imdb_id,popularity,budget,revenue,director,runtime,genres,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
original_title,,,,,,,,,,,,,,
Inception,27205,tt1375666,9.363643,160000000,825500000,Christopher Nolan,148,Action|Thriller|Science Fiction|Mystery|Adventure,7/14/2010,9767,7.9,2010,1.600000e+08,8.255000e+08
The Avengers,24428,tt0848228,7.637767,220000000,1519557910,Joss Whedon,143,Science Fiction|Action|Adventure,4/25/2012,8903,7.3,2012,2.089437e+08,1.443191e+09
Avatar,19995,tt0499549,9.432768,237000000,2781505847,James Cameron,162,Action|Adventure|Fantasy|Science Fiction,12/10/2009,8458,7.1,2009,2.408869e+08,2.827124e+09
The Dark Knight,155,tt0468569,8.466668,185000000,1001921825,Christopher Nolan,152,Drama|Action|Crime|Thriller,7/16/2008,8432,8.1,2008,1.873655e+08,1.014733e+09
Django Unchained,68718,tt1853728,5.944518,100000000,425368238,Quentin Tarantino,165,Drama|Western,12/25/2012,7375,7.7,2012,9.497443e+07,4.039911e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Top Dog,36278,tt0114697,0.018196,6000000,5093707,Aaron Norris,86,Action|Adventure|Comedy|Family|Thriller,4/28/1995,10,4.7,1995,8.585801e+06,7.288926e+06
Beautiful,21033,tt1170391,0.159638,1500000,56000,Dean O'Flaherty,97,Drama|Mystery|Thriller,4/27/2009,10,4.4,2009,1.524601e+06,5.691842e+04
Club Paradise,26555,tt0090856,0.167621,15000000,12308521,Harold Ramis,96,Comedy|Drama|Romance,7/11/1986,10,4.1,1986,2.984110e+07,2.448665e+07
Best Defense,11221,tt0086955,0.174241,18000000,19265302,Willard Huyck,94,Action|Comedy,7/20/1984,10,3.8,1984,3.778276e+07,4.043868e+07
Down,19058,tt0247303,0.128169,15000000,163169,Dick Maas,111,Action|Horror|Mystery|Thriller,5/11/2001,10,3.7,2001,1.847232e+07,2.009407e+05

In [83]:
filtered_tmdbs.set_index('original_title', inplace= True)
#Set the index to the title to make it easier to pull values from different columns

In [117]:
filtered_tmdbs['genres']= filtered_tmdbs['genres'].str.split("|", n= 1, expand = True)
filtered_tmdbs.head(20)

<ipython-input-117-b27f4473554e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_tmdbs['genres']= filtered_tmdbs['genres'].str.split("|", n= 1, expand = True)

,id,imdb_id,popularity,budget,revenue,director,runtime,genres,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
original_title,,,,,,,,,,,,,,
Inception,27205,tt1375666,9.363643,160000000,825500000,Christopher Nolan,148,Action,7/14/2010,9767,7.9,2010,1.600000e+08,8.255000e+08
The Avengers,24428,tt0848228,7.637767,220000000,1519557910,Joss Whedon,143,Science Fiction,4/25/2012,8903,7.3,2012,2.089437e+08,1.443191e+09
Avatar,19995,tt0499549,9.432768,237000000,2781505847,James Cameron,162,Action,12/10/2009,8458,7.1,2009,2.408869e+08,2.827124e+09
The Dark Knight,155,tt0468569,8.466668,185000000,1001921825,Christopher Nolan,152,Drama,7/16/2008,8432,8.1,2008,1.873655e+08,1.014733e+09
Django Unchained,68718,tt1853728,5.944518,100000000,425368238,Quentin Tarantino,165,Drama,12/25/2012,7375,7.7,2012,9.497443e+07,4.039911e+08
The Hunger Games,70160,tt1392170,2.571099,75000000,691210692,Gary Ross,142,Science Fiction,3/12/2012,7080,6.7,2012,7.123082e+07,6.564734e+08
Iron Man 3,68721,tt1300854,4.946136,200000000,1215439994,Shane Black,130,Action,4/18/2013,6882,6.9,2013,1.872067e+08,1.137692e+09
The Dark Knight Rises,49026,tt1345836,6.591277,250000000,1081041287,Christopher Nolan,165,Action,7/16/2012,6723,7.5,2012,2.374361e+08,1.026713e+09
Interstellar,157336,tt0816692,24.949134,165000000,621752480,Christopher Nolan,169,Adventure,11/5/2014,6498,8.0,2014,1.519800e+08,5.726906e+08
The Hobbit: An Unexpected Journey,49051,tt0903624,4.218933,250000000,1017003568,Peter Jackson,169,Adventure,11/26/2012,6417,6.9,2012,2.374361e+08,9.658933e+08
The Matrix,603,tt0133093,7.753899,63000000,463517383,Lilly Wachowski|Lana Wachowski,136,Action,3/30/1999,6351,7.8,1999,8.247033e+07,6.067687e+08
Iron Man,1726,tt0371746,4.977955,140000000,585174222,Jon Favreau,126,Action,4/30/2008,6220,7.3,2008,1.417901e+08,5.926566e+08
Mad Max: Fury Road,76341,tt1392190,28.419936,150000000,378436354,George Miller,120,Action,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
Skyfall,37724,tt1074638,5.603587,200000000,1108561013,Sam Mendes,143,Action,10/25/2012,6137,6.8,2012,1.899489e+08,1.052849e+09
The Lord of the Rings: The Fellowship of the Ring,120,tt0120737,8.575419,93000000,871368364,Peter Jackson,178,Adventure,12/18/2001,6079,7.8,2001,1.145284e+08,1.073080e+09
Fight Club,550,tt0137523,8.947905,63000000,100853753,David Fincher,139,Drama,10/14/1999,5923,8.1,1999,8.247033e+07,1.320229e+08
The Shawshank Redemption,278,tt0111161,7.192039,25000000,28341469,Frank Darabont,142,Drama,9/10/1994,5754,8.4,1994,3.677779e+07,4.169346e+07
The Lord of the Rings: The Return of the King,122,tt0167260,7.122455,94000000,1118888979,Peter Jackson,201,Adventure,12/1/2003,5636,7.9,2003,1.114231e+08,1.326278e+09
Guardians of the Galaxy,118340,tt2015381,14.311205,170000000,773312399,James Gunn,121,Action,7/30/2014,5612,7.9,2014,1.565855e+08,7.122911e+08
Jurassic World,135397,tt0369610,32.985763,150000000,1513528810,Colin Trevorrow,124,Action,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09

In [97]:
def searchByGenre(genre):
    number = 0
    count = 0
    for each in filtered_tmdbs['genres']:
        if genre in each:
            count += 1
    return count
print(searchByGenre('Crime'))

652

In [119]:
genre_mean= filtered_tmdbs.groupby(['genres']).mean()
#just trying to find a way to find the genre with the highest vote counts and averages. I think this works we'll see
#ask how to get genres sorted

In [120]:
genre_mean.head(20)
#finally got the genres in one word, so I'm going to make a visualization on the average vote_average for each genre!

,id,popularity,budget,revenue,runtime,vote_count,vote_average,release_year,budget_adj,revenue_adj
genres,,,,,,,,,,
Action,33729.246734,1.442326,5.174563e+07,1.359287e+08,110.484761,723.486212,5.996517,2000.780842,6.105521e+07,1.626525e+08
Adventure,26021.455414,1.905525,7.232108e+07,2.288291e+08,114.802548,985.627389,6.250955,1998.834395,8.615973e+07,3.041586e+08
Animation,43003.310680,1.712723,8.001165e+07,2.761320e+08,90.233010,917.912621,6.361165,2005.067961,8.541191e+07,2.959841e+08
Comedy,36644.514612,0.914765,2.621832e+07,7.879489e+07,102.142313,322.728081,6.017154,2001.813215,3.105447e+07,1.006022e+08
Crime,39351.755814,1.072113,2.597616e+07,7.097316e+07,114.720930,442.901163,6.451744,1999.395349,3.179085e+07,9.784828e+07
Documentary,29738.375000,0.289461,4.464192e+06,2.146299e+07,101.968750,68.250000,6.656250,2004.750000,4.925998e+06,2.363154e+07
Drama,46020.991011,0.927571,2.466313e+07,6.476240e+07,117.651685,379.400000,6.437978,2002.016854,3.088464e+07,9.096426e+07
Family,59070.550000,1.609295,6.037500e+07,2.175372e+08,93.475000,667.800000,6.100000,2002.225000,6.744876e+07,2.728411e+08
Fantasy,29688.818182,1.581660,5.541864e+07,1.595936e+08,104.518182,699.481818,6.080000,2000.563636,6.405080e+07,1.943293e+08
History,88127.705882,1.442235,3.533053e+07,1.136145e+08,129.294118,554.411765,6.494118,2002.529412,4.993716e+07,1.680665e+08
Horror,39252.705455,0.855787,1.525382e+07,5.507483e+07,97.770909,310.363636,5.749818,1999.447273,1.946227e+07,7.877088e+07
Music,43775.689655,0.914098,3.217241e+07,7.742144e+07,107.965517,234.931034,6.193103,1998.034483,4.301774e+07,1.285718e+08
Mystery,54661.916667,1.133780,3.048417e+07,7.211830e+07,106.611111,433.500000,6.136111,2001.750000,3.670193e+07,8.748986e+07
Romance,58643.424242,1.369972,2.794857e+07,1.017852e+08,107.636364,514.136364,6.451515,2003.318182,3.175368e+07,1.242896e+08
Science Fiction,37155.959184,1.931437,5.279701e+07,1.738652e+08,110.520408,1061.602041,6.244898,1999.428571,6.250739e+07,2.171706e+08
TV Movie,15691.000000,0.273628,5.000000e+06,4.200000e+07,89.000000,35.000000,5.600000,1996.000000,6.951084e+06,5.838910e+07
Thriller,59635.600000,1.171430,3.357948e+07,7.880660e+07,110.268750,510.575000,5.993125,2004.662500,3.778419e+07,9.109040e+07
War,68127.400000,1.658497,5.721000e+07,1.334856e+08,128.100000,702.700000,6.480000,2002.800000,6.410168e+07,1.405774e+08
Western,51463.750000,1.193918,4.612500e+07,7.996166e+07,121.937500,425.875000,6.418750,1993.562500,6.188450e+07,1.158031e+08

In [ ]:
def searchbyGenre(genre):
    genre_filtered_tmbdbs